backend/HealthMonitor/HealthMonitor/HealthMonitor/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls', namespace='main')),
]

backend/HealthMonitor/HealthMonitor/Main/urls.py
from django.urls import path
from Main import views

app_name = 'main'

urlpatterns = [
	path('', views.index, name='index'),
	path('login', views.login_view, name='login'),
	path('register', views.register_view, name='register'),
	path('dashboard', views.dashboard, name='user-dash'),
	path('patient/<int:patient_id>', views.patient_details_view, name='patient-dash'),
	path('patient/<int:patient_id>/records', views.patient_record_view, name='record'),
]

backend/HealthMonitor/HealthMonitor/Main/models.py
from django.db import models
from django.core import validators

import datetime
import uuid

# Create your models here.
class Patient(models.Model):
	patient_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	first_name = models.CharField(max_length=50, default="FirstName")
	last_name = models.CharField(max_length=50, default="LastName")
	dob = models.DateField(default=datetime.date.today)

	def __str__(self):
		today = datetime.date.today()
		age = today.year - self.dob.year - ((today.month, today.day) < (dob.month, dob.day))
		return f'Name: {first_name} {last_name}; Age: {age}'

class MedicalRecord(models.Model):
	patient_id = models.ForeignKey(Patient, default=uuid.uuid4, on_delete=models.CASCADE)
	rec_type = models.CharField(max_length=100, default="Blood Pressure")
	rec_value = models.CharField(max_length=100, default="0/0 mm of Hg")
	day = models.IntegerField(
		default=1, 
		validators=[
			validators.MinValueValidator(1),
			validators.MaxValueValidator(31)
		]
	)
	month = models.IntegerField(
		default=1, 
		validators=[
			validators.MinValueValidator(1),
			validators.MaxValueValidator(12)
		]
	)
	year = models.IntegerField(
		default=2023, 
		validators=[validators.MinValueValidator(2023),]
	)

	def __str__(self):
		return f'{self.patient_id}: {self.day}-{self.month}-{self.year}'

backend/HealthMonitor/HealthMonitor/Main/forms.py
from django import forms
from django.core import validators

from django.contrib.auth.models import User

class RegisterForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'email', 'password']

class LoginForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['username', 'password']

backend/HealthMonitor/HealthMonitor/Main/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate
from django.contrib.auth.models import User

from Main.forms import RegisterForm, LoginForm

# dummy data

dummy_patients = [
	{
		"patient_id": 1,
		"first_name": "Malati",
		"last_name": "Chakraborty",
		"dob": "15-08-1947",
		"age": 75
	},
	{
		"patient_id": 2,
		"first_name": "Debasish",
		"last_name": "Chakraborty",
		"dob": "03-10-1961",
		"age": 61
	},
	{
		"patient_id": 3,
		"first_name": "Uttara",
		"last_name": "Chakraborty",
		"dob": "02-12-1968",
		"age": 54
	},
	{
		"patient_id": 4,
		"first_name": "Archisman",
		"last_name": "Chakraborty",
		"dob": "26-01-1999",
		"age": 24
	}
]

dummy_records = [
	{
		"type": "Blood Pressure",
		"value": "139/68 mm Hg",
		"day": 4,
		"month": 12,
		"year": 2022
	},
	{
		"type": "Blood Pressure",
		"value": "133/69 mm Hg",
		"day": 4,
		"month": 1,
		"year": 2023
	},
	{
		"type": "Blood Pressure",
		"value": "122/74 mm Hg",
		"day": 4,
		"month": 2,
		"year": 2023
	},
	{
		"type": "Blood Pressure",
		"value": "124/77 mm Hg",
		"day": 4,
		"month": 3,
		"year": 2023
	},
	{
		"type": "Blood Pressure",
		"value": "119/70 mm Hg",
		"day": 4,
		"month": 4,
		"year": 2023
	},
	{
		"type": "Blood Pressure",
		"value": "127/73 mm Hg",
		"day": 4,
		"month": 5,
		"year": 2023
	}
]

# Create your views here.

def index(request):

	if request.method == 'POST':
		registerForm = RegisterForm(request.POST)
		loginForm = LoginForm(request.POST)

		if loginForm.is_valid():
			username, password = loginForm.cleaned_data.values()
			print(f'Trying to login: {username}/{password}')
		elif registerForm.is_valid():
			username, first_name, last_name, password, re_password  = registerForm.cleaned_data.values()
			print(f'Trying to register::' \
				f'{username}/{password}/{re_password}: {first_name} {last_name}'
			)
		else:
			print('Invalid Data!!')
	else:
		print('Invalid Method Invoked!')

	inputs = {
		'login': [
			{'name': 'username', 'type': 'text', 'label': 'Username'}, 
			{'name': 'password', 'type': 'password', 'label': 'Password'}, 
		],
		'register': [
			{'name': 'first_name', 'type': 'text', 'label': 'First Name'}, 
			{'name': 'last_name', 'type': 'text', 'label': 'Last Name'},
			{'name': 'username', 'type': 'text', 'label': 'Username'}, 
			{'name': 'email', 'type': 'email', 'label': 'Email ID'}, 
			{'name': 'password', 'type': 'password', 'label': 'Password'}, 
			{'name': 're_password', 'type': 'password', 'label': 'Confirm Password'}, 
		]
	}
	
	return render(request, 'main/index.html', context=inputs)

def login_view(request):
	if request.method == 'POST':		
		loginForm = LoginForm(request.POST)

		if loginForm.is_valid():
			username, password = loginForm.cleaned_data.values()
			print(f'Trying to login: {username}/{password}')
		else:
			print('Invalid Data!!')
	else:
		print('Invalid Method Invoked!')

	return dashboard(request)

def register_view(request):
	if request.method == 'POST':
		registerForm = RegisterForm(request.POST)

		if registerForm.is_valid():
			username, first_name, last_name, password, re_password  = registerForm.cleaned_data.values()
			print(f'Trying to register::' \
				f'{username}/{password}/{re_password}: {first_name} {last_name}'
			)
		else:
			print('Invalid Data!!')
	else:
		print('Invalid Method Invoked!')

	return dashboard(request)

def dashboard(request):
	patient_details = [
		{
			"patient_id": patient["patient_id"],
			"first_name": patient["first_name"],
			"last_name": patient["last_name"]
		} for patient in dummy_patients
	]

	content = {
		'page_desc': "This is going to be a user dashboard page",
		'patient_list': patient_details			
	}

	return render(request, 'main/dashboard.html', context=content)

def patient_details_view(request, patient_id):

	patient_details = [patient for patient in dummy_patients if patient["patient_id"] == patient_id]
	records = [ f"{rec['day']}-{rec['month']}-{rec['year']}" for rec in dummy_records ]

	content = {
		'page_desc': "Patient Dashboard",
		'details': patient_details[0],
		'records': records
	}
	return render(request, 'main/patientDetails.html', context=content)

def patient_record_view(request, patient_id):	
	record_date = request.GET['recid']
	day, month, year = [int(part) for part in record_date.split("-")]
	record = [rec for rec in dummy_records 
		if rec['day'] == day and rec['month'] == month and rec['year'] == year
	]

	content = {
		'patient_id': patient_id,
		'record_date': record_date,
		'details': record[0]
	}
	return render(request, 'main/patientRecord.html', context=content)

backend/HealthMonitor/HealthMonitor/templates/main/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>	
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
	<title>User Dashboard</title>
</head>
<body>
	<div class="container">
		<h1>{{ page_desc }}</h1>
		
		<ul>
			{% for patient in patient_list %}
			<li>
				<a href="{% url 'main:patient-dash' patient.patient_id %}">
					{{ patient.patient_id }}: {{ patient.first_name }} {{ patient.last_name }}
				</a>
			</li>
			{% endfor %}
		</ul>
	</div>
</body>
</html>

backend/HealthMonitor/HealthMonitor/templates/main/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" data-bs-theme="dark">

<head>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
		integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/indexStyles.css' %}">
	
	<title>Health Monitoring App</title>
</head>

<body class="bg-dark bg-gradient text-white">

	<div class="container-fluid p-5">

		<h1 class="text-center">Health Monitoring Application</h1>

		<div class="container-fluid d-flex justify-content-center align-items-center">

			<div id="login-form" class="container p-4 m-5 border border-5 border-success rounded">
				<form action="{% url 'main:login' %}" method="POST">
					{% for field in login %}
					<div class="row mb-3">
						<label for="{{ field.name }}" class="col-lg-2 col-form-label">
							{{ field.label }}
						</label>
						<div class="col-lg-9">
							<input type="{{ field.type }}" name="{{ field.name }}" class="form-control">
						</div>
					</div>
					{% endfor %}

					{% csrf_token %}

					<div class="row mb-3">
						<div class="col-lg-5">
							<button type="submit" class="btn btn-lg btn-success">
								Login
							</button>
						</div>
					</div>
				</form>
			</div>

			<div id="register-form" class="container p-4 m-5 border border-5 border-primary rounded">
				<form action="{% url 'main:register' %}" method="POST">					
					{% for field in register %}
						<div class="row mb-3">
						<label for="{{ field.name }}" class="col-lg-2 col-form-label">
							{{ field.label }}
						</label>
						<div class="col-lg-9">
							<input type="{{ field.type }}" name="{{ field.name }}" class="form-control">
						</div>
					</div>
					{% endfor %}
					
					{% csrf_token %}

					<div class="row mb-3">
						<div class="col-lg-5">
							<button type="submit" class="btn btn-lg btn-primary">
								Register
							</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>



</body>

</html>

backend/HealthMonitor/HealthMonitor/templates/main/patientDetails.html
<!DOCTYPE html>
<html lang="en">
<head>	
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
	<title>Patient Details Page</title>
</head>
<body>
	<div class="container">
		<h1>{{ page_desc }}</h1>

		<label for="patient-id">Patient ID:</label>
		<b>{{ details.patient_id }}</b><br>

		<label for="name">Name:</label>
		<b>{{ details.first_name }} {{ details.last_name }}</b><br>

		<label for="dob">Date of Birth:</label>
		<b>{{ details.dob }}</b><br>

		<label for="age">Age:</label>
		<b>{{ details.age }}</b><br>

		<h3>Records::::::></h3>
		<ul>
			{% for date in records %}
			<li>
				<a href="{% url 'main:record' details.patient_id %}?recid={{ date }}">
					{{ date }}
				</a>
			</li>
			{% endfor %}
		</ul>

	</div>
</body>
</html>

backend/HealthMonitor/HealthMonitor/templates/main/patientRecord.html
<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
	<title>Patient Medical Record</title>
</head>
<body>
	<div class="container">
		<p>Record Details for</p>
		<span>Patient ID:</span> <b>{{ patient_id }}</b><br>
		<span>Record Date:</span> <b>{{ record_date }}</b><br>
		<span>Record Type:</span> <b>{{ details.type }}</b><br>
		<span>Record Value:</span> <b>{{ details.value }}</b><br>
	</div>
</body>
</html>